[package]
name = "dndhelper"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11.2"
bevy_asset_loader = { version = "0.17.0", features = ["standard_dynamic_assets"] }
bevy_common_assets = {version = "0.7.0" ,features = ["ron"]}
bevy_egui = "0.21.0"
getrandom = { version = "0.2.10", features = ["js"] }
hexx = "0.10.0"
rand = "0.8.5"
ron = "0.8.1"
serde = "1.0.187"
