[package]
name = "dndhelper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
bevy_asset_loader = "0.17.0"
bevy_egui = "0.21.0"
getrandom = {version = "0.2.10", features = ["js"]}
hexx = "0.10.0"
rand = "0.8.5"
